- name: Install Go for Apple Silicone to ~/.local/bin/
  unarchive:
    src: https://go.dev/dl/go{{ go_version }}.{{ ansible_system | lower }}-arm64.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    remote_src: yes
    mode: '0550'
    owner: "{{ ansible_user_id }}"
  when: ansible_architecture == "arm64"

- name: Install Go for x86_64 to ~/.local/bin/
  unarchive:
    src: https://go.dev/dl/go{{ go_version }}.{{ ansible_system | lower }}-amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    remote_src: yes
    mode: '0550'
    owner: "{{ ansible_user_id }}"
  when: ansible_architecture == "x86_64"
