- name: Setup Development Machine
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - ./vars/macos_defaults.yml

  roles:
    - role: base
      tags: base
    - role: gcloud
      tags: gcloud
    - role: git
      tags: git
    - role: golang
      tags: golang
    - role: kubernetes
      tags: kubernetes
    - role: nodenv
      tags: nodenv
    - role: pyenv
      tags: pyenv
    - role: rbenv
      tags: rbenv
    - role: oh-my-zsh
      tags: oh-my-zsh
    - role: terraform
      tags: terraform
    - role: vim
      tags: vim
