- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME}}/.oh-my-zsh/oh-my-zsh.sh"

- name: Git checkout zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    accept_hostkey: yes

- name: Git checkout zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    accept_hostkey: yes

- name: Rsync custom oh-my-zsh overrides
  ansible.posix.synchronize:
    src: oh-my-zsh/
    dest: "{{ ansible_env.HOME}}/.oh-my-zsh/custom"
    recursive: yes

- name: Change zsh theme in ~/.zshrc
  lineinfile:
    path: "{{ ansible_env.HOME}}/.zshrc"
    regexp: '^ZSH_THEME='
    line: ZSH_THEME="juanghurtado"

- name: Add plugin zsh names to ~/.zshrc
  lineinfile:
    path: "{{ ansible_env.HOME}}/.zshrc"
    regexp: '^plugins='
    line: plugins=(git colored-man-pages helm pyenv python docker golang extract zsh-syntax-highlighting zsh-autosuggestions kubectl minikube)
