- debug:
    var: kind_version

- name: Download Kind for Apple Silicon to ~/.local/bin/
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/v{{ kind_version }}/kind-{{ ansible_system | lower }}-arm64
    dest: "{{ ansible_env.HOME }}/.local/bin/kind"
    mode: '0550'
    owner: "{{ ansible_user_id }}"
  when: ansible_architecture == "arm64"

- name: Download Kind for x86_64 to ~/.local/bin/
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/v{{ kind_version }}/kind-{{ ansible_system | lower }}-amd64
    dest: "{{ ansible_env.HOME }}/.local/bin/kind"
    mode: '0550'
    owner: "{{ ansible_user_id }}"
  when: ansible_architecture == "amd64"
