- name: Set kubectl version to latest if not kubectl_version
  when: kubectl_version is not defined
  set_fact:
    kubectl_version: $(curl -L -s https://dl.k8s.io/release/stable.txt)

- debug:
    var: kubectl_version

- name: Install kubectl version {{ kubectl_version }} for arm64
  get_url:
    url: https://dl.k8s.io/release/v{{ kubectl_version  }}/bin/{{ ansible_system | lower }}/arm64/kubectl
    dest: ~/.local/bin/kubectl
    mode: '0550'
    owner: "{{ ansible_user_id }}"
  when: ansible_architecture == "arm64"

- name: Install kubectl version {{ kubectl_version }} for x86_64
  get_url:
    url: https://dl.k8s.io/release/v{{ kubectl_version  }}/bin/{{ ansible_system | lower }}/amd64/kubectl
    dest: ~/.local/bin/kubectl
    mode: '0550'
    owner: "{{ ansible_user_id }}"
  when: ansible_architecture == "x86_64"
