- name: Install Terraform version {{ terraform_version }} for Apple Silicon
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_arm64.zip
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
    mode: '0550'
    owner: "{{ ansible_env.USER }}"
  when: ansible_architecture == "arm64"
  tags: install-terraform

- name: Install Terraform version {{ terraform_version }} for x86_64
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
    mode: '0550'
    owner: "{{ ansible_env.USER }}"
  when: ansible_architecture == "amd64"
  tags: install-terraform
