- name: Install MacOS Pyenv Dependecies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - openssl
    - readline
    - sqlite3
    - xz
    - zlib
  tags: install-pyenv

- name: Git clone pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: "{{ ansible_env.HOME}}/.pyenv"
    accept_hostkey: yes
  tags: install-pyenv

- name: Git clone pyenv-virtualenv
  git:
    repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
    dest: "{{ ansible_env.HOME}}/.pyenv/plugins/pyenv-virtualenv"
    accept_hostkey: yes
  tags: install-pyenv

- name: Git clone pyenv-update
  git:
    repo: 'https://github.com/pyenv/pyenv-update.git'
    dest: "{{ ansible_env.HOME}}/.pyenv/plugins/pyenv-update"
    accept_hostkey: yes
  tags: install-pyenv

- name: Install python 2 and 3 with with --enable-framework for Mac OSX
  shell: ~/.pyenv/bin/pyenv install {{ item }}
  args:
    creates: ~/.pyenv/versions/{{ item }}/bin/python
  loop:
    - "{{ python_version }}"
    - "{{ python2_version }}"
  tags: install-python

- name: Set python global version to {{ python_version }}
  shell: "{{ ansible_env.HOME}}/.pyenv/bin/pyenv global {{ python_version }}"
  tags: install-python
