- name: Install CLI APT packages
  become: yes
  apt:
    update_cache: yes
    autoremove: yes
    pkg:
      - build-essential
      - curl
      - make
      - cmake
      - silversearcher-ag
      - sqlite3
      - zsh
      - tmux
      - jq
      - vim

- name: Change user shell to zsh for Linux
  become: yes
  command: chsh -s /usr/bin/zsh

- name: Copy zshrc to ~/.zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    # Do not overwrite if exists, important because of oh-my-zsh edits the file
    force: no

# Linux requires pyenv to be on both .zprofile and .profile
- name: Copy zprofile to ~/.profile
  template:
    src: zprofile
    dest: ~/.profile
  tags:
    - zprofile-config
