- name: Mac OS install tasks
  include: macos.yml
  when: ansible_system == "Darwin"

- name: Linux install tasks
  include: linux.yml
  when: ansible_system == "Linux"

- name: Create local binaries directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: "{{ ansible_user_id }}"
  loop:
    - "{{ ansible_env.HOME }}/.local"
    - "{{ ansible_env.HOME }}/.local/bin"
  tags:
    - always
    - create-local-bin

- name: Copy zprofile to ~/.zprofile
  template:
    src: zprofile
    dest: "{{ ansible_env.HOME}}/.zprofile"
  tags:
    - always
    - zsh-dotfiles

- name: Copy zshrc to ~/.myzshrc
  template:
    src: zshrc
    dest: "{{ ansible_env.HOME}}/.myzshrc"
  tags:
    - always
    - zsh-dotfiles

- name: Ensure ~/.myzshrc is sourced when shell is started
  ignore_errors: yes
  lineinfile:
    path: "{{ ansible_env.HOME}}/.zshrc"
    state: present
    line: source {{ ansible_env.HOME}}/.myzshrc
