- name: Create local binaries directory
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: directory
    mode: '0750'
    owner: "{{ ansible_user_id }}"
  tags:
    - vim-config

- name: Copy common files to ~/.vim/
  copy:
    src: common/
    dest: "{{ ansible_env.HOME}}/.vim/"
  tags:
    - vim-config

- name: Copy vimrc to ~/.vimrc
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME}}/.vimrc"
  tags:
    - vim-config
