########## Pyenv ##########
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv > /dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

if command -v pyenv > /dev/null 2>&1; then
  eval "$(pyenv virtualenv-init -)"
fi

if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi
