########## Pyenv ##########
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv > /dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

if command -v pyenv > /dev/null 2>&1; then
  eval "$(pyenv virtualenv-init -)"
fi

########## Homebrew ##########
if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
